development:
  s3_url: 'https://buuqit-test.s3.amazonaws.com/'
  domains: 'lvh.me,localhost,dev.thebookingfactory.com,app.thebookingfactory.com,thebookingfactory.com,192.168.1.151,factory.com'
  views_path: 'views'
production:
  s3_url: 'https://buuqit-dev.s3.amazonaws.com/'
  domains: 'lvh.me,localhost,dev.thebookingfactory.com,app.thebookingfactory.com,thebookingfactory.com,192.168.1.151,54.194.140.144'
  views_path: '/templates/views'
